spring.application.name=backend
spring.config.import=optional:classpath:.env.properties

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.open-in-view=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
